export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const FILTER_CRITERIA = {
    FILTER_PRODUCTS_BY_GENDER: "FILTER_PRODUCTS_BY_GENDER",
    FILTER_PRODUCTS_BY_STYLE: "FILTER_PRODUCTS_BY_STYLE",
    FILTER_PRODUCTS_BY_COLOR: "FILTER_PRODUCTS_BY_COLOR",

}

export const CART = {
    ADD_TO_CART: "FILTER_PRODUCTS_BY_SIZE",
    REMOVE_FROM_CART: "REMOVE_FROM_CART"
}


export const FETCH_SHOES = {
    FETCH_PRODUCTS_PENDING: 'FETCH_PRODUCTS_PENDING',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR'
}

export const UPDATE_QUANTITY_PRODUCTS = {
    UPDATE_QUANTITY_PENDING: 'UPDATE_QUANTITY_PENDING',
    UPDATE_QUANTITY_SUCCESS: 'UPDATE_QUANTITY_SUCCESS',
    UPDATE_QUANTITY_ERROR: 'UPDATE_QUANTITY_ERROR'
}

export const TROLLEY = {
    ADD_PRODUCT_TROLLEY: "ADD_PRODUCT_TROLLEY",
    REMOVE_PRODUCT_TROLLEY: "REMOVE_PRODUCT_TROLLEY",
    UPDATE_QUANTITY: "UPDATE_QUANTITY"
}